spring:
  application:
    name: expresscart

  data:
    mongodb:
      host: localhost
      port: 27017
      database: express-cart
    redis:
      host: localhost
      port: 6379
      password: password

  cache:
    redis:
      time-to-live: 60000